#!/bin/bash

xhost +local:root > /dev/null
docker run --rm -it \
  -e "JTAG_SERVER=$JTAG_SERVER" \
  -e "JTAG_PASSWD=$JTAG_PASSWD" \
  -v $(pwd):/build \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
  -v ~/.altera.quartus:/root/.altera.quartus \
  --ipc=host \
  --privileged \
  --cap-drop=ALL \
  --security-opt=no-new-privileges \
  docker.pkg.github.com/featherbear/unsw-comp3222/quartus-13.0sp1:latest \
  /usr/local/bin/quartus_wrapper "$@"
xhost -local:root > /dev/null
