LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY mux8 IS
	PORT (
		IN_A 		: IN  STD_LOGIC_VECTOR(7 DOWNTO 0);
		IN_B 		: IN  STD_LOGIC_VECTOR(7 DOWNTO 0);
		OUTPUT 	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
		SW			: IN  STD_LOGIC
	);
END mux8;

ARCHITECTURE func OF mux8 IS
BEGIN
	PROCESS (SW, IN_A, IN_B) BEGIN
		IF SW = '0' THEN
			OUTPUT <= IN_A;
		ELSE
			OUTPUT <= IN_B;
		END IF;
	END PROCESS;
END func;